### PR TITLE
rotation response added

### PR DESCRIPTION
**Pull request by concach**
This PR adds an additional layout view which becomes active when the device is rotated to landscape position. The layout is changed to place buttons and text in locations that make more sense for a landscape orientation. See below for screenshots of portrait and landscape modes. 

Known defect: The current activity is terminated upon phone rotation, which means the scores reset. Suggestions on how to fix this would be very appreciated. 

portrait orientation

landscape orientation

### CODE REVIEW

**Comment by BobGu** [comment]
http://stackoverflow.com/questions/3329318/android-how-to-not-destroy-the-activity-when-i-rotate-the-device

**Comment by BobGu** [comment]
Also you do research on the activity lifecycle in Android.  Probably one of the fundamental building blocks in building an Android application.

**Comment by concach** [comment]
@BobGu Thanks! Very easy fix.

**Comment by matthewecampbell** [comment]
@concach - I don't know much about Android development, but it looks like you may be using static layouts for your front end?  If that's true, my one suggestion is making them responsive which isn't a terribly time consuming fix.  Other than that the screenshots look awesome!

**Pull request merged**
